[package]
name = "secret_structs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secret_macros = {path = "../macros"}
serde = { version = "1.0", features = ["derive"] }
glam = { version = "0.18", features = ["serde"] }
unicode-segmentation = "1.9.0"
libc = "0.2.0"

[features]
default = ["benchmarking"]
benchmarking = []
